# Generated by Django 5.0.6 on 2024-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cont01', '0003_department2_employee2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_no',
            field=models.IntegerField(default=101),
        ),
    ]
